# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for tw-patcher.

This produces a one-folder distribution containing the CLI + GUI.
The GUI is launched via `tw-patcher ui`.

Icon files are expected in build/icons/ (generated by scripts/generate_icons.py).
"""

import platform
from pathlib import Path

block_cipher = None

ROOT = Path(SPECPATH)
ICONS_DIR = ROOT / "icons"

# Determine platform-specific icon
system = platform.system()
if system == "Windows":
    icon_file = str(ICONS_DIR / "icon.ico")
elif system == "Darwin":
    icon_file = str(ICONS_DIR / "icon.icns")
else:
    icon_file = None

a = Analysis(
    [str(ROOT / "tw_patcher" / "__main__.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "tw_patcher",
        "tw_patcher.__main__",
        "tw_patcher.cli",
        "tw_patcher.config",
        "tw_patcher.console",
        "tw_patcher.exceptions",
        "tw_patcher.utils",
        "tw_patcher.clients",
        "tw_patcher.clients.rpfm",
        "tw_patcher.clients.steam",
        "tw_patcher.models",
        "tw_patcher.models.game",
        "tw_patcher.models.pack",
        "tw_patcher.models.workshop",
        "tw_patcher.services",
        "tw_patcher.services.extraction",
        "tw_patcher.services.repacking",
        "tw_patcher.services.scaffold",
        "tw_patcher.services.system",
        "tw_patcher.ui",
        "tw_patcher.ui.app",
        "tw_patcher.ui.main_window",
        "tw_patcher.ui.state",
        "tw_patcher.ui.styles",
        "tw_patcher.ui.widgets",
        "tw_patcher.ui.workers",
        "tw_patcher.ui.dialogs",
        "tw_patcher.ui.dialogs.game_browser",
        "tw_patcher.ui.dialogs.workshop_browser",
        "tw_patcher.ui.panels",
        "tw_patcher.ui.panels.extract_panel",
        "tw_patcher.ui.panels.game_panel",
        "tw_patcher.ui.panels.repack_panel",
        "tw_patcher.ui.panels.settings_panel",
        "tw_patcher.ui.widgets.game_card",
        "tw_patcher.ui.widgets.log_viewer",
        "tw_patcher.ui.widgets.thumbnail",
        "tw_patcher.ui.widgets.workshop_mod",
        "tw_patcher.ui.workers.artwork",
        "tw_patcher.ui.workers.extract",
        "tw_patcher.ui.workers.repack",
        "tw_patcher.ui.workers.workshop",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="tw-patcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)

# GUI-only executable (windowed, no console window)
# Uses a separate Analysis for the GUI entry point but shares all deps via COLLECT
gui_a = Analysis(
    [str(ROOT / "tw_patcher" / "__gui__.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "tw_patcher",
        "tw_patcher.ui",
        "tw_patcher.ui.app",
        "tw_patcher.ui.main_window",
        "tw_patcher.ui.state",
        "tw_patcher.ui.styles",
        "tw_patcher.ui.widgets",
        "tw_patcher.ui.workers",
        "tw_patcher.ui.dialogs",
        "tw_patcher.ui.dialogs.game_browser",
        "tw_patcher.ui.dialogs.workshop_browser",
        "tw_patcher.ui.panels",
        "tw_patcher.ui.panels.extract_panel",
        "tw_patcher.ui.panels.game_panel",
        "tw_patcher.ui.panels.repack_panel",
        "tw_patcher.ui.panels.settings_panel",
        "tw_patcher.ui.widgets.game_card",
        "tw_patcher.ui.widgets.log_viewer",
        "tw_patcher.ui.widgets.thumbnail",
        "tw_patcher.ui.widgets.workshop_mod",
        "tw_patcher.ui.workers.artwork",
        "tw_patcher.ui.workers.extract",
        "tw_patcher.ui.workers.repack",
        "tw_patcher.ui.workers.workshop",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

gui_pyz = PYZ(gui_a.pure, gui_a.zipped_data, cipher=block_cipher)

gui_exe = EXE(
    gui_pyz,
    gui_a.scripts,
    [],
    exclude_binaries=True,
    name="tw-patcher-gui",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)

# Merge shared dependencies into a single dist folder
MERGE((a, "tw-patcher", "tw-patcher"), (gui_a, "tw-patcher-gui", "tw-patcher-gui"))

coll = COLLECT(
    exe,
    gui_exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    gui_a.binaries,
    gui_a.zipfiles,
    gui_a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="tw-patcher",
)

# macOS .app bundle (only used on macOS builds)
if system == "Darwin":
    app = BUNDLE(
        coll,
        name="TW Mod Patcher.app",
        icon=icon_file,
        bundle_identifier="com.tw-patcher.app",
        info_plist={
            "CFBundleShortVersionString": "0.3.0",
            "CFBundleVersion": "0.3.0",
            "NSHighResolutionCapable": True,
        },
    )
